/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RssDotxmlRouteImport } from "./routes/rss[.]xml";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthSignupIndexRouteImport } from "./routes/_auth/signup/index";
import { Route as AuthSigninIndexRouteImport } from "./routes/_auth/signin/index";

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: "/rss.xml",
  path: "/rss.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: "/_auth/signup/",
  path: "/signup/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: "/_auth/signin/",
  path: "/signin/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/rss.xml": typeof RssDotxmlRoute;
  "/signin/": typeof AuthSigninIndexRoute;
  "/signup/": typeof AuthSignupIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/rss.xml": typeof RssDotxmlRoute;
  "/signin": typeof AuthSigninIndexRoute;
  "/signup": typeof AuthSignupIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/rss.xml": typeof RssDotxmlRoute;
  "/_auth/signin/": typeof AuthSigninIndexRoute;
  "/_auth/signup/": typeof AuthSignupIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/rss.xml" | "/signin/" | "/signup/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/rss.xml" | "/signin" | "/signup";
  id: "__root__" | "/" | "/rss.xml" | "/_auth/signin/" | "/_auth/signup/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RssDotxmlRoute: typeof RssDotxmlRoute;
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute;
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/rss.xml": {
      id: "/rss.xml";
      path: "/rss.xml";
      fullPath: "/rss.xml";
      preLoaderRoute: typeof RssDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/signup/": {
      id: "/_auth/signup/";
      path: "/signup";
      fullPath: "/signup/";
      preLoaderRoute: typeof AuthSignupIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/signin/": {
      id: "/_auth/signin/";
      path: "/signin";
      fullPath: "/signin/";
      preLoaderRoute: typeof AuthSigninIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
