/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RssDotxmlRouteImport } from "./routes/rss[.]xml";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AuthSignupIndexRouteImport } from "./routes/_auth/signup/index";
import { Route as AuthSigninIndexRouteImport } from "./routes/_auth/signin/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: "/rss.xml",
  path: "/rss.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: "/_auth/signup/",
  path: "/signup/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: "/_auth/signin/",
  path: "/signin/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/rss.xml": typeof RssDotxmlRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/signin/": typeof AuthSigninIndexRoute;
  "/signup/": typeof AuthSignupIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/rss.xml": typeof RssDotxmlRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/signin": typeof AuthSigninIndexRoute;
  "/signup": typeof AuthSignupIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/rss.xml": typeof RssDotxmlRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/_auth/signin/": typeof AuthSigninIndexRoute;
  "/_auth/signup/": typeof AuthSignupIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/rss.xml"
    | "/dashboard/"
    | "/api/auth/$"
    | "/signin/"
    | "/signup/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/rss.xml" | "/dashboard" | "/api/auth/$" | "/signin" | "/signup";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/rss.xml"
    | "/dashboard/"
    | "/api/auth/$"
    | "/_auth/signin/"
    | "/_auth/signup/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  RssDotxmlRoute: typeof RssDotxmlRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute;
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/rss.xml": {
      id: "/rss.xml";
      path: "/rss.xml";
      fullPath: "/rss.xml";
      preLoaderRoute: typeof RssDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/_auth/signup/": {
      id: "/_auth/signup/";
      path: "/signup";
      fullPath: "/signup/";
      preLoaderRoute: typeof AuthSignupIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/signin/": {
      id: "/_auth/signin/";
      path: "/signin";
      fullPath: "/signin/";
      preLoaderRoute: typeof AuthSigninIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
